on:
  pull_request:
  push:
    branches:
      - "main"
jobs:
  nix-eval-jobs:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.nix-eval-jobs.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            accept-flake-config = true
      - uses: cachix/cachix-action@v12
        with:
          name: nixpkgs-maintained
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - id: nix-eval-jobs
        name: nix-eval-jobs
        shell: bash
        run: |
          jobsJSON=$(nix run github:nix-community/nix-eval-jobs -- --flake .#packages.x86_64-linux)

          # Push derivations
          while IFS= read -r job; do
            drvPath=$(echo "$job" | jq -r .drvPath)
            cachix push nixpkgs-maintained "$drvPath"
          done <<< "$jobsJSON"

          jobs=$(echo "$jobsJSON" | nix run nixpkgs#jq -- -c -s .)

          cachix push nixpkgs-maintained /nix/store/s700l2cd59bnsfppzsxv9ysvmn5gyg3c-cowsay-3.7.0.drv

          echo matrix="$jobs" >> $GITHUB_OUTPUT

  nix-build:
    needs: nix-eval-jobs
    strategy:
      matrix:
        package: ${{ fromJSON(needs.nix-eval-jobs.outputs.matrix) }}
    runs-on: ubuntu-latest # TODO: job
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            accept-flake-config = true
      - uses: cachix/cachix-action@v12
        with:
          name: nixpkgs-maintained
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build ${{ matrix.package.drvPath }}
