on:
  pull_request:
  push:
    branches:
      - "main"
jobs:
  nix-eval-jobs:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.nix-eval-jobs.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            accept-flake-config = true
      - uses: cachix/cachix-action@v12
        with:
          name: nixpkgs-maintained
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - id: nix-eval-jobs
        name: nix-eval-jobs
        shell: bash
        run: |
          jobs=$(nix run github:nix-community/nix-eval-jobs -- --check-cache-status --flake .#packages.x86_64-linux | nix run nixpkgs#jq -- -c -s '.|filter(.isCached == false)')
          echo matrix="$jobs" >> $GITHUB_OUTPUT
  nix-build:
    needs: nix-eval-jobs
    strategy:
      matrix:
        package: ${{ fromJSON(needs.nix-eval-jobs.outputs.matrix) }}
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            accept-flake-config = true
      - uses: cachix/cachix-action@v12
        with:
          name: nixpkgs-maintained
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build .#packages.${{ matrix.package.system }}.${{ matrix.package.attr }}
