on:
  pull_request:
  push:
    branches:
      - "main"
jobs:
  nix-eval-jobs:
    runs-on: ubuntu-latest
    outputs:
          matrix: ${{ steps.nix-eval-jobs.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            accept-flake-config = true
      - id: nix-eval-jobs
        name: nix-eval-jobs
        shell: bash
        run: |
          jobs=$(run nix run github:nix-community/nix-eval-jobs -- --flake .#packages.x86_64-linux | nix run nixpkgs#jq -- -s .)
          echo matrix="$jobs" >> $GITHUB_OUTPUT

  nix-build:
    needs: nix-eval-jobs
    strategy:
      matrix: ${{ fromJSON(needs.nix-eval-jobs.outputs.matrix )}}
    runs-on: ubuntu-latest # TODO: job
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            accept-flake-config = true
      - name: ".#packages.${{ matrix.system }}.${{ matrix.attr }}"
        run:
          nix-store --realise ${{ matrix.drvPath }}
